authors:
  ngyngcphu:
    name: Nguyễn Ngọc Phú
    description: Software developer
    avatar: https://avatars.githubusercontent.com/u/111476687?v=4
    url: https://github.com/ngyngcphu

  amyranotamirror:
    name: Nguyễn Thanh Hiền
    description: Product Manager & Business Analyst & UI/UX Designer
    avatar: https://avatars.githubusercontent.com/u/87921251?v=4
    url: https://github.com/amyranotamirror

  quannhg:
    name: Nguyễn Hồng Quân
    description: Software developer
    avatar: https://avatars.githubusercontent.com/u/128902312?v=4
    url: https://github.com/quannhg

  baotram153:
    name: Đặng Ngọc Bảo Trâm
    description: Scientific researcher
    avatar: https://avatars.githubusercontent.com/u/56596545?v=4
    url: https://github.com/baotram153

  VuHuy-cse-9:
    name: Vũ Nguyễn Minh Huy
    description: Scientific researcher
    avatar: https://avatars.githubusercontent.com/u/57817188?v=4
    url: https://github.com/VuHuy-cse-9

  BaoDuong:
    name: Dương Gia Bảo
    description: Software developer
    avatar: https://avatars.githubusercontent.com/u/155243724?v=4
    url: https://github.com/BaoDuong254
